### PR TITLE
Cog 382 refactor demo notebook

### PR DESCRIPTION
**Pull request by dexters1**
Combining all demo notebooks into one single notebook

## Summary by CodeRabbit

- **Documentation**
	- Updated links in the README.md for the Google Colab notebook.
- **Chores**
	- Deleted outdated Jupyter notebooks (cognee_demo_1.5.ipynb and full_run.ipynb) that contained examples of job descriptions and data processing tasks.

### CODE REVIEW

**Review by Vasilije1990 — CHANGES_REQUESTED** [review]
remove: Some common questions
This tool is not a replacement for vector databases or Langchain, it's an extension
We want to help map the old data world to the new one
Local models and evals are on the roadmap
The relationships in the graph are customizable, so is the graph model. It is something we will continue exploring

**Comment by Vasilije1990** [comment]
Refactor the initial text you added, I think it is fine but it is a bit dated, and it could look better, and have a more consistent look. Some pics are grainy, text of different sizes, some pics have bad visibility.

I did a lot of this in 2 hours for some meetup, so would be good to give it a fresh go

**Comment by dexters1** [comment]
Do we want to have successful code output already as part of the notebook? Or as part of the google colab?

**Comment by dexters1** [comment]
Should we handle installation of dependencies and setting up of virtual environment as part of the Jupyter Notebook? Or just for the google colab?

**Comment by dexters1** [comment]
What should we use regarding default databases for the Notebook? Would the following work:
Networkx for the graph database
LanceDB for the vector database 
Sqlite for the relational database

**Comment by dexters1** [comment]
os.environ["LLM_API_KEY"] = "YOUR OPENAI_API_KEY" no longer works from python code for setting LLM key, it's only read from the .env file currently. Should we support this again? If not we need to update README and notebook

**Comment by Vasilije1990** [comment]
> os.environ["LLM_API_KEY"] = "YOUR OPENAI_API_KEY" no longer works from python code for setting LLM key, it's only read from the .env file currently. Should we support this again? If not we need to update README and notebook

Hm, did you test this in collab? It should work

**Comment by Vasilije1990** [comment]
> What should we use regarding default databases for the Notebook? Would the following work: Networkx for the graph database LanceDB for the vector database Sqlite for the relational database

Yes, that is the default embedded option

**Comment by Vasilije1990** [comment]
> Should we handle installation of dependencies and setting up of virtual environment as part of the Jupyter Notebook? Or just for the google colab?

Why? It should be done with pip install cognee as a lib

**Comment by Vasilije1990** [comment]
> Do we want to have successful code output already as part of the notebook? Or as part of the google colab?

Search is included, would need to be refactored to the latest search tasks Boris deployed yesterday. Chat with him on it. fyi @borisarzentar

**Comment by dexters1** [comment]
> > os.environ["LLM_API_KEY"] = "YOUR OPENAI_API_KEY" no longer works from python code for setting LLM key, it's only read from the .env file currently. Should we support this again? If not we need to update README and notebook
> 
> Hm, did you test this in collab? It should work

It's working for me now both in colab and in a local notebook, not sure why I had those issues yesterday

**Pull request merged**
